### ISSUE TITLE
Launch in collapsed mode by default

### ISSUE THREAD

**Issue by jankeromnes** [nt1m/c9.ide.reviewcomments#2]
When installing this plugin, it installs a panel on the right IDE tab, but the panel is open by default when you start Cloud9, which is confusing because it instantly grabs the user's attention.

I believe it should start collapsed by default.

**Comment by nt1m** [comment]
This code should do it: https://github.com/nt1m/c9.ide.reviewcomments/blob/master/c9.ide.reviewcomments.js#L50-L53
